apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: raushank-echo
spec:
  finalizers:
  - kubernetes
---
apiVersion: serving.kubeflow.org/v1alpha1
kind: KFService
metadata:
  annotations:
    mir.azureml.k8s.io/modelservice-tls-mode: disabled
    mirName: raushankmir-pb
    pathBasedRouting: "true"
    sourceName: raushank-echo-pb
    mir.azureml.k8s.io/init-container-image: raushan2016/helloworld-console:v1
  labels:
    mir.azureml.k8s.io/resource-group: devrg-mir-release-int-westus2
    mir.azureml.k8s.io/subscription-id: e54229a3-0e6f-40b3-82a1-ae9cda6e2b8
    mir.azureml.k8s.io/enable-model-mount: "true"
    mir.azureml.k8s.io/mir-display-name: raushankmir-1
    mir.azureml.k8s.io/mir-name: raushankmir-1
    mir.azureml.k8s.io/modelservice-display-name: echo-pb
    mir.azureml.k8s.io/modelservice-gateway-name: echo-pb
    mir.azureml.k8s.io/modelservice-name: echo-pb
    mir.azureml.k8s.io/modelsource-display-name: raushank-echo
    mir.azureml.k8s.io/modelsource-name: raushank-echo
    mir.azureml.k8s.io/parent-name: raushank-echo
  name: echo-pb
  namespace: raushank-echo
spec:
  default:
    custom:
      container:
        image: nginxdemos/hello
        ports:
        - containerPort: 80
        name: user-container
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 200Mi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 0
          initialDelaySeconds: 310
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 0
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
    maxReplicas: 1
    minReplicas: 1
    serviceAccountName: default
